import { describe, expect, it } from "vitest";
import { buildAgentCommandSummary } from "@/features/agents/summary";

describe("buildAgentCommandSummary", () => {
  it("prioritizes failed and active jobs and counts actionable outcomes", () => {
    const summary = buildAgentCommandSummary({
      isOnline: false,
      jobs: [
        {
          id: "job_done",
          agent_id: "meta-ads",
          status: "done",
          prompt: "Finished sync",
          result: "ok",
          error: null,
          created_at: "2026-03-05T10:00:00.000Z",
          started_at: "2026-03-05T10:00:00.000Z",
          finished_at: "2026-03-05T10:05:00.000Z",
        },
        {
          id: "job_running",
          agent_id: "tm-monitor",
          status: "running",
          prompt: "Checking events",
          result: null,
          error: null,
          created_at: "2026-03-06T11:00:00.000Z",
          started_at: "2026-03-06T11:01:00.000Z",
          finished_at: null,
        },
        {
          id: "job_error",
          agent_id: "meta-ads",
          status: "error",
          prompt: "Sync campaigns",
          result: null,
          error: "Token expired",
          created_at: "2026-03-06T10:00:00.000Z",
          started_at: "2026-03-06T10:00:00.000Z",
          finished_at: "2026-03-06T10:02:00.000Z",
        },
      ],
      lastSeen: "2026-03-06T11:58:00.000Z",
      now: new Date("2026-03-06T12:00:00.000Z"),
      outcomes: [
        {
          action: "triage",
          agentId: "assistant",
          assetFollowUpItemId: null,
          assetId: null,
          assetName: null,
          campaignId: "cmp_1",
          campaignName: "Launch",
          clientSlug: "zamora",
          completedAt: "2026-03-06T09:00:00.000Z",
          createdAt: "2026-03-06T08:00:00.000Z",
          crmContactId: null,
          crmContactName: null,
          crmFollowUpItemId: null,
          errorText: null,
          eventFollowUpItemId: null,
          eventId: null,
          eventName: null,
          linkedActionItemId: null,
          linkedAssetFollowUpItemId: null,
          linkedCrmFollowUpItemId: null,
          linkedEventFollowUpItemId: null,
          requestDetail: null,
          requestSummary: "Needs next step",
          resultText: "Recommend a new launch task",
          startedAt: "2026-03-06T08:05:00.000Z",
          status: "done",
          taskId: "task_done",
          visibility: "shared",
        },
        {
          action: "triage",
          agentId: "assistant",
          assetFollowUpItemId: null,
          assetId: null,
          assetName: null,
          campaignId: "cmp_2",
          campaignName: "Follow-up",
          clientSlug: "zamora",
          completedAt: null,
          createdAt: "2026-03-06T11:00:00.000Z",
          crmContactId: null,
          crmContactName: null,
          crmFollowUpItemId: null,
          errorText: null,
          eventFollowUpItemId: null,
          eventId: null,
          eventName: null,
          linkedActionItemId: null,
          linkedAssetFollowUpItemId: null,
          linkedCrmFollowUpItemId: null,
          linkedEventFollowUpItemId: null,
          requestDetail: null,
          requestSummary: "Still queued",
          resultText: null,
          startedAt: null,
          status: "pending",
          taskId: "task_pending",
          visibility: "shared",
        },
      ],
    });

    expect(summary.metrics).toEqual([
      expect.objectContaining({
        key: "runtime",
        tone: "critical",
        value: "Offline",
      }),
      expect.objectContaining({
        key: "running",
        tone: "neutral",
        value: 1,
      }),
      expect.objectContaining({
        key: "failed_recent",
        tone: "critical",
        value: 1,
      }),
      expect.objectContaining({
        key: "actionable_outcomes",
        tone: "neutral",
        value: 2,
      }),
    ]);
    expect(summary.attentionJobs.map((job) => job.id)).toEqual([
      "job_error",
      "job_running",
    ]);
  });
});
