import { describe, expect, it } from "vitest";
import { countActionableAgentOutcomes } from "@/features/operations-center/summary";

describe("operations center summary", () => {
  it("counts queued and untriaged agent outcomes as actionable follow-through", () => {
    expect(
      countActionableAgentOutcomes([
        {
          action: "triage",
          agentId: "assistant",
          assetFollowUpItemId: null,
          assetId: null,
          assetName: null,
          campaignId: "cmp_1",
          campaignName: "Launch",
          clientSlug: "zamora",
          completedAt: null,
          createdAt: "2026-03-06T10:00:00.000Z",
          errorText: null,
          eventFollowUpItemId: null,
          eventId: null,
          eventName: null,
          linkedActionItemId: null,
          linkedAssetFollowUpItemId: null,
          linkedEventFollowUpItemId: null,
          requestDetail: null,
          requestSummary: "Queued assistant triage",
          resultText: null,
          startedAt: null,
          status: "pending",
          taskId: "task_1",
          visibility: "admin_only",
        },
        {
          action: "review",
          agentId: "meta-ads",
          assetFollowUpItemId: null,
          assetId: null,
          assetName: null,
          campaignId: "cmp_1",
          campaignName: "Launch",
          clientSlug: "zamora",
          completedAt: "2026-03-06T10:05:00.000Z",
          createdAt: "2026-03-06T10:01:00.000Z",
          errorText: null,
          eventFollowUpItemId: null,
          eventId: null,
          eventName: null,
          linkedActionItemId: null,
          linkedAssetFollowUpItemId: null,
          linkedEventFollowUpItemId: null,
          requestDetail: null,
          requestSummary: "Meta recommendation ready",
          resultText: "Use new creative in ad set",
          startedAt: "2026-03-06T10:02:00.000Z",
          status: "done",
          taskId: "task_2",
          visibility: "admin_only",
        },
        {
          action: "review",
          agentId: "meta-ads",
          assetFollowUpItemId: null,
          assetId: null,
          assetName: null,
          campaignId: "cmp_1",
          campaignName: "Launch",
          clientSlug: "zamora",
          completedAt: "2026-03-06T10:06:00.000Z",
          createdAt: "2026-03-06T10:03:00.000Z",
          errorText: null,
          eventFollowUpItemId: null,
          eventId: null,
          eventName: null,
          linkedActionItemId: "action_123",
          linkedAssetFollowUpItemId: null,
          linkedEventFollowUpItemId: null,
          requestDetail: null,
          requestSummary: "Meta recommendation already linked",
          resultText: "Already converted into next step",
          startedAt: "2026-03-06T10:04:00.000Z",
          status: "done",
          taskId: "task_3",
          visibility: "admin_only",
        },
      ]),
    ).toBe(2);
  });

});
