import { describe, expect, it } from "vitest";
import { buildOperationsCenterSnapshot, countActionableAgentOutcomes } from "@/features/operations-center/summary";

describe("operations center summary", () => {
  it("counts queued and untriaged agent outcomes as actionable follow-through", () => {
    expect(
      countActionableAgentOutcomes([
        {
          action: "triage",
          agentId: "assistant",
          assetFollowUpItemId: null,
          assetId: null,
          assetName: null,
          campaignId: "cmp_1",
          campaignName: "Launch",
          clientSlug: "zamora",
          completedAt: null,
          createdAt: "2026-03-06T10:00:00.000Z",
          crmContactId: null,
          crmContactName: null,
          crmFollowUpItemId: null,
          errorText: null,
          eventFollowUpItemId: null,
          eventId: null,
          eventName: null,
          linkedActionItemId: null,
          linkedAssetFollowUpItemId: null,
          linkedCrmFollowUpItemId: null,
          linkedEventFollowUpItemId: null,
          requestDetail: null,
          requestSummary: "Queued assistant triage",
          resultText: null,
          startedAt: null,
          status: "pending",
          taskId: "task_1",
          visibility: "admin_only",
        },
        {
          action: "review",
          agentId: "meta-ads",
          assetFollowUpItemId: null,
          assetId: null,
          assetName: null,
          campaignId: "cmp_1",
          campaignName: "Launch",
          clientSlug: "zamora",
          completedAt: "2026-03-06T10:05:00.000Z",
          createdAt: "2026-03-06T10:01:00.000Z",
          crmContactId: null,
          crmContactName: null,
          crmFollowUpItemId: null,
          errorText: null,
          eventFollowUpItemId: null,
          eventId: null,
          eventName: null,
          linkedActionItemId: null,
          linkedAssetFollowUpItemId: null,
          linkedCrmFollowUpItemId: null,
          linkedEventFollowUpItemId: null,
          requestDetail: null,
          requestSummary: "Meta recommendation ready",
          resultText: "Use new creative in ad set",
          startedAt: "2026-03-06T10:02:00.000Z",
          status: "done",
          taskId: "task_2",
          visibility: "admin_only",
        },
        {
          action: "review",
          agentId: "meta-ads",
          assetFollowUpItemId: null,
          assetId: null,
          assetName: null,
          campaignId: "cmp_1",
          campaignName: "Launch",
          clientSlug: "zamora",
          completedAt: "2026-03-06T10:06:00.000Z",
          createdAt: "2026-03-06T10:03:00.000Z",
          crmContactId: null,
          crmContactName: null,
          crmFollowUpItemId: null,
          errorText: null,
          eventFollowUpItemId: null,
          eventId: null,
          eventName: null,
          linkedActionItemId: "action_123",
          linkedAssetFollowUpItemId: null,
          linkedCrmFollowUpItemId: null,
          linkedEventFollowUpItemId: null,
          requestDetail: null,
          requestSummary: "Meta recommendation already linked",
          resultText: "Already converted into next step",
          startedAt: "2026-03-06T10:04:00.000Z",
          status: "done",
          taskId: "task_3",
          visibility: "admin_only",
        },
      ]),
    ).toBe(2);
  });

  it("builds the activity snapshot from the shared backbone", () => {
    const snapshot = buildOperationsCenterSnapshot({
      actionCenter: {
        approvals: [{ id: "approval_1" } as never, { id: "approval_2" } as never],
        crmFollowUps: [{ id: "crm_1" } as never],
        discussions: [{ id: "discussion_1" } as never, { id: "discussion_2" } as never, { id: "discussion_3" } as never],
      },
      agentOutcomes: [
        {
          action: "triage",
          agentId: "assistant",
          assetFollowUpItemId: null,
          assetId: null,
          assetName: null,
          campaignId: "cmp_1",
          campaignName: "Launch",
          clientSlug: "zamora",
          completedAt: null,
          createdAt: "2026-03-06T10:00:00.000Z",
          crmContactId: null,
          crmContactName: null,
          crmFollowUpItemId: null,
          errorText: null,
          eventFollowUpItemId: null,
          eventId: null,
          eventName: null,
          linkedActionItemId: null,
          linkedAssetFollowUpItemId: null,
          linkedCrmFollowUpItemId: null,
          linkedEventFollowUpItemId: null,
          requestDetail: null,
          requestSummary: "Queued assistant triage",
          resultText: null,
          startedAt: null,
          status: "pending",
          taskId: "task_1",
          visibility: "admin_only",
        },
      ],
      assetSummary: {
        attentionAssets: [],
        metrics: [
          { key: "total_assets", label: "Total assets", value: 5 },
          { key: "needs_review", label: "Needs review", value: 2 },
          { key: "approved_assets", label: "Approved", value: 1 },
          { key: "linked_assets", label: "Linked to campaigns", value: 3 },
        ],
      },
      events: [
        {
          actorId: null,
          actorName: "Jaime",
          actorType: "user",
          clientSlug: "zamora",
          createdAt: "2026-03-06T11:00:00.000Z",
          detail: null,
          entityId: "cmp_1",
          entityType: "campaign",
          eventName: "campaign_updated",
          id: "event_1",
          metadata: {},
          pageId: null,
          summary: "Updated campaign pacing",
          taskId: null,
          visibility: "shared",
        },
      ],
    });

    expect(snapshot.lastSharedEventAt).toBe("2026-03-06T11:00:00.000Z");
    expect(snapshot.metrics).toEqual([
      expect.objectContaining({ key: "pending_approvals", value: 2 }),
      expect.objectContaining({ key: "open_discussions", value: 3 }),
      expect.objectContaining({ key: "crm_follow_ups", value: 1 }),
      expect.objectContaining({ key: "agent_follow_through", value: 1 }),
      expect.objectContaining({ key: "assets_needing_review", value: 2 }),
    ]);
  });
});
